apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rh32eu5il-python 
  janus-idp.io/tekton: rh32eu5il-python
  backstage.io/kubernetes-id: rh32eu5il-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rh32eu5il-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml