apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rh32eu5il-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh32eu5il-python 
  name: rh32eu5il-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rh32eu5il-python 
